package br.com.fastfps.chunk;
import br.com.fastfps.FastFpsConfig;import br.com.fastfps.render.DynamicBudget;import br.com.fastfps.api.IFastFpsPipeline;import java.util.*;import java.util.concurrent.*;
public final class ChunkUpdateManager implements IFastFpsPipeline{
 private final Map<Long,ChunkSectionState> states=new HashMap<Long,ChunkSectionState>(1024);private final ChunkUpdateQueue queue=new ChunkUpdateQueue();private final ExecutorService workers;
 private volatile boolean protectedMode;private volatile float frameMs;private volatile int running;private int px,pz;private float dirX,dirZ;
 public ChunkUpdateManager(){workers=Executors.newFixedThreadPool(FastFpsConfig.MAX_WORKERS,new ThreadFactory(){public Thread newThread(Runnable r){Thread t=new Thread(r,"FastFps-Chunk");t.setDaemon(true);return t;}});}
 public synchronized void setCamera(int x,int z,float dx,float dz){px=x;pz=z;dirX=dx;dirZ=dz;}
 public synchronized void request(int x,int z,int base,int cost){long k=ChunkKey.of(x,z);ChunkSectionState s=states.get(k);if(s==null){s=new ChunkSectionState();states.put(k,s);}long g=s.invalidate();s.stage(ChunkStage.MESH_PENDING);if(queue.size()>=FastFpsConfig.MAX_QUEUE_SIZE)return;int p=base+ChunkPriority.score(x,z,px,pz,dirX,dirZ,true,true,FastFpsConfig.PREDICTIVE_LOADING);queue.offer(new ChunkUpdateTask(k,g,p,Math.max(1,cost)),FastFpsConfig.MAX_QUEUE_SIZE);}
 public void tick(DynamicBudget b){frameMs=b.frameTimeMillis();protectedMode=FastFpsConfig.PROTECTED_MODE&&(frameMs>FastFpsConfig.PROTECTED_FRAME_MS||queue.size()>FastFpsConfig.PROTECTED_QUEUE_SIZE);int n=protectedMode?1:FastFpsConfig.MAX_BUILDS_PER_TICK;if(queue.size()>FastFpsConfig.MAX_QUEUE_SIZE/2)n=1;for(int i=0;i<n;i++){final ChunkUpdateTask t=queue.poll();if(t==null)break;final ChunkSectionState s; synchronized(this){s=states.get(t.key);}if(s==null||s.generation()!=t.generation)continue;s.stage(ChunkStage.MESH_BUILDING);running++;workers.execute(new Runnable(){public void run(){try{if(s.generation()==t.generation)s.stage(ChunkStage.MESH_READY);else s.stage(ChunkStage.OBSOLETE);}finally{running--;}}});}}
 public boolean isProtectedMode(){return protectedMode;}public int getPendingChunkTasks(){return queue.size();}public int getPendingUploads(){return 0;}public float getFrameTimeMillis(){return frameMs;}public void requestChunk(int x,int z,int p){request(x,z,p,1);}public int runningWorkers(){return running;}public synchronized void clear(){queue.clear();states.clear();}
}
